// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xXWoocel1fynQVxfvVIEJwLRhA7RNVQ',
    appId: '1:716121008876:web:8e48f917f9aa6bd9ef93c9',
    messagingSenderId: '716121008876',
    projectId: 'mynotes-hangh',
    authDomain: 'mynotes-hangh.firebaseapp.com',
    storageBucket: 'mynotes-hangh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhv4jQWBuVOtZ4m5amqHnJSpQ1QDktiyM',
    appId: '1:716121008876:android:834a24b635c1a8ccef93c9',
    messagingSenderId: '716121008876',
    projectId: 'mynotes-hangh',
    storageBucket: 'mynotes-hangh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5MYSAsslgGwoF0l_dS-Vc9ziFBQs5im8',
    appId: '1:716121008876:ios:5ab8796a89d4b1e8ef93c9',
    messagingSenderId: '716121008876',
    projectId: 'mynotes-hangh',
    storageBucket: 'mynotes-hangh.firebasestorage.app',
    iosBundleId: 'com.exampleDomain.exampleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5MYSAsslgGwoF0l_dS-Vc9ziFBQs5im8',
    appId: '1:716121008876:ios:5ab8796a89d4b1e8ef93c9',
    messagingSenderId: '716121008876',
    projectId: 'mynotes-hangh',
    storageBucket: 'mynotes-hangh.firebasestorage.app',
    iosBundleId: 'com.exampleDomain.exampleapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2xXWoocel1fynQVxfvVIEJwLRhA7RNVQ',
    appId: '1:716121008876:web:acf867528af09564ef93c9',
    messagingSenderId: '716121008876',
    projectId: 'mynotes-hangh',
    authDomain: 'mynotes-hangh.firebaseapp.com',
    storageBucket: 'mynotes-hangh.firebasestorage.app',
  );
}
